[TKT-18,TKT-20,TKT-22,TKT-24] - #4/feat/sign up,sign in,resign,exist user
wisoft-graduate/quotation-api-server pull request #14
Opened 2024-03-19 08:45 UTC by kukjun

# 요구사항 및 기능 요약
User의 회원가입, 로그인, 탈퇴, 중복조회 기능 구현

# 관련 자료
- 설계 자료
  - [회원가입](https://www.notion.so/c94739e206a3473899a09374ff06ad65?pvs=4)
  - [로그인](https://www.notion.so/2eea0426d6034ba99e6b586228b32c2c?pvs=4)
  - [중복조회](https://www.notion.so/450f4fe3f7aa4e2780a2c07d3653269f?pvs=4)
  - [탈퇴](https://www.notion.so/2748a58b79c4443a8ad7953dd6adb162?pvs=4)

# 작업 종류
- [x] 기능 추가

# 코드 리뷰 시 참고 사항
- Service에 비지니스 로직이 다 들어가 있음.
- Port를 이용해서 조회 시, 만약 Null 값을 가져오게 되면, 이를 Adapter에서 처리해야 할지, 비지니스 로직에서 처리해야 할지 의견 바람

2024-03-19 10:05 UTC, qkrcksduf requested changes

2024-03-19 10:05 UTC, qkrcksduf commented on src/main/kotlin/wisoft/io/quotation/adaptor/in/http/UserController.kt
> +    @GetMapping("/users/exist")
@kukjun 이전에 설계 할때 exist를 사용하는 것으로 설계하긴 했는데. restful 원칙상 users/{userId}/existence or /users?id={id}&nickname={nickname} 등과 같이 단순 사용자 조회 API와 통합하는 것이 더 좋아 보이는데 어떠신가요?

2024-03-19 10:05 UTC, qkrcksduf commented on src/main/kotlin/wisoft/io/quotation/adaptor/in/http/UserController.kt
> +        // FIXME : NO_CONTENT 는 본문 자체가 없어야 함.
@kukjun 삭제 api로 이해했고 응답에 id가 있을 필요는 없을 것 같아요. (논의 필요) id를 사용한다고 결정해도 202는 적합하지 않은 것 같아요(비동기 처리 시 사용, 이후 처리 될 것이나 미리 응답 시) id를 사용한다고 결정하면 200, 사용하지 않을 것이라면 204가 적합해 보입니다.

2024-03-19 10:05 UTC, qkrcksduf commented on src/main/kotlin/wisoft/io/quotation/adaptor/in/http/UserController.kt
> +    fun resign(@PathVariable("id") id: String): ResponseEntity<ResignUseCase.ResignResponse> {
@kukjun regisn은 익숙한 단어라는 생각이 안들어요. 우리 메소드 이름은 조회는 get, 나머지는 create, update, delete 사용하기로 했으니 convention 대로 가는게 좋을 것 같아요.

2024-03-19 10:05 UTC, qkrcksduf commented on src/main/kotlin/wisoft/io/quotation/application/service/UserService.kt
> +        val leaveCount = findLeaveUserListCountPort.findLeaveUsersCount()
@kukjun 데이터베이스에서 현재 leave count를 +1해주는 방식으로 이해했는데 좋은 방법은 아닌 것 같아요. 데이터베이스 동시성 문제로 인해 데이터가 중복될 수 있고, 추가로 데이터베이스를 한번 거치면서 네트워크 비용을 소모할 필요가 있을까 하는 생각이 드네요. 그냥 겹치지 않는 문자를 만드는 패턴을 하나 정의해서 사용하는 것이 좋지 않을까 생각합니다.

2024-03-19 10:05 UTC, qkrcksduf commented on src/main/kotlin/wisoft/io/quotation/util/JWTUtil.kt
> +    private const val SECRET_KEY = "8kTcEnj4ABscsjcWVOg06brYjyOwwVwdMB7s1BGwzBQDhmASi"
@kukjun 보안상 환경 변수나 yaml 파일 값을 사용할 수 있도록 수정하는 것이 좋아 보여요.

2024-03-19 10:05 UTC, qkrcksduf commented on src/main/kotlin/wisoft/io/quotation/application/port/out/FindUserByIdPort.kt
> +    fun findByIdOrNull(id: String): User
@kukjun convention 대로 get으로 가시죠~ 다른 부분에 사용한 find도 동일하게 get으로 수정 부탁드려요.

2024-03-19 10:05 UTC, qkrcksduf commented on src/main/kotlin/wisoft/io/quotation/adaptor/in/http/UserController.kt
> +                    status = HttpStatus.OK.value()
@kukjun ResponseEntity에서 상태값을 응답해주고 있는데 따로 Response에 status를 넣은 이유가 궁금해요.

2024-03-19 10:18 UTC, qkrcksduf commented on src/main/kotlin/wisoft/io/quotation/application/port/out/FindUserByIdPort.kt
> +    fun findByIdOrNull(id: String): User
@kukjun 어떤 부분에서 예외처리를 하는게 좋을까는 굉장히 고민이 되네요. 어댑터 계층에서 예외 처리를 하는 경우 빠르게 캐치 및 대응이 가능하나 비즈니스 로직과 관련된 예외처리를 하게 됨으로써 헥사고날 아키텍처의 원칙과 어긋날 수 있을 것 같아요. 그래서 저는 예외는 전반적으로 비즈니스 레이어에서 처리하는게 좋다고 생각해요.

2024-03-21 13:44 UTC, kukjun reviewed
Code Review에 대한 피드백입니다.

2024-03-21 13:44 UTC, kukjun commented on src/main/kotlin/wisoft/io/quotation/adaptor/in/http/UserController.kt
> +                    status = HttpStatus.OK.value()
[Notion API 설계 문서](https://www.notion.so/API-82b0b9300a6c435faeaf29227c58ac73?pvs=4)

해당 API 설계 시, status를 response에 담아서 보내주도록 처음에 논의했었습니다. 그래서 status를 넣어서 작성했고, 만약 이렇게 하게 된다면, Status Code를 Frontend에서 굳이 Header를 파싱하지 않아도 된다는 장점이 있을 수 있겠네요

2024-03-21 13:44 UTC, kukjun commented on src/main/kotlin/wisoft/io/quotation/adaptor/in/http/UserController.kt
> +    @GetMapping("/users/exist")
1번 users/{userId}/existence 를 사용하게 되면, nickname 중복 검사가 api로 따로 나와야 할 거 같습니다.
2번으로 하게 된다면, user list의 정보를 돌려주는 api될 것 같습니다. 비 로그인 사용자에게 User에 세부 정보를 돌려줄 필요가 있을까요?

2024-03-21 13:44 UTC, kukjun commented on src/main/kotlin/wisoft/io/quotation/adaptor/in/http/UserController.kt
> +    fun resign(@PathVariable("id") id: String): ResponseEntity<ResignUseCase.ResignResponse> {
아하 usecase만 으로 이해했습니다. 수정하겠습니다. 그런데, soft delete, 와 hard delete는 구분해야 하지 않을까요?

2024-03-21 13:44 UTC, kukjun commented on src/main/kotlin/wisoft/io/quotation/adaptor/in/http/UserController.kt
> +        // FIXME : NO_CONTENT 는 본문 자체가 없어야 함.
응답 id를 없애는 쪽으로 하는게 좋을 것 같네요. 그렇게 수정하겠습니다.

2024-03-21 13:44 UTC, kukjun commented on src/main/kotlin/wisoft/io/quotation/application/port/out/FindUserByIdPort.kt
> +    fun findByIdOrNull(id: String): User
비지니스 레이어에서 하는걸로 하겠습니다.

2024-03-21 13:44 UTC, kukjun commented on src/main/kotlin/wisoft/io/quotation/application/service/UserService.kt
> +        val leaveCount = findLeaveUserListCountPort.findLeaveUsersCount()
요구사항에서, 탈퇴한유저를 처리하는 방법에 대해서 논의한 결과였는데요, 이 부분은 요구사항이 변경되는 부분이라서, 어떻게 할지 논의를 할 필요가 있어보입니다.

2024-03-21 13:44 UTC, kukjun commented on src/main/kotlin/wisoft/io/quotation/util/JWTUtil.kt
> +    private const val SECRET_KEY = "8kTcEnj4ABscsjcWVOg06brYjyOwwVwdMB7s1BGwzBQDhmASi"
넵 👍

2024-03-21 13:44 UTC, kukjun commented on src/main/kotlin/wisoft/io/quotation/adaptor/in/http/UserController.kt
> +    fun resign(@PathVariable("id") id: String): ResponseEntity<ResignUseCase.ResignResponse> {
delete로 처리했습니다.

2024-03-26 08:08 UTC, kukjun commented
### 아직 활성화하지 않은 작업
* 에러 메시지 처리시, 사용자 정의 Exception 만들어서 처리
* Test Code 작성하기

해당 내용에 대해서는 Exception Handler가 Main에 PR된 이후에 작업하는게 좋을 것 같아서 이번 PR에서 제외했습니다.

2024-03-27 09:53 UTC, qkrcksduf commented on src/main/kotlin/wisoft/io/quotation/adaptor/out/persistence/repository/UserCustomRepository.kt
> +                andCount += 1
andCount를 사용한 이유가 WHERE 절 때문인 것 같은데 WHERE 1=1 로 맨처음에 써두고 시작하면 코드 훨씬 깔끔해 질거에요.

2024-03-27 09:53 UTC, qkrcksduf commented on src/main/kotlin/wisoft/io/quotation/application/port/in/CreateUserUseCase.kt
>          val id: String,
@kukjun id, nickname 둘다 필수 맞나요? 이거에 따라 서비스쪽 코드 변경해야 될 것 같아요.

2024-03-27 09:53 UTC, qkrcksduf commented on src/main/kotlin/wisoft/io/quotation/application/service/UserService.kt
> +            val ids = LinkedList<String>()
@kukjun 사용할때 listOf 함수 사용하시면 돼요.

2024-03-27 09:53 UTC, qkrcksduf commented on src/main/kotlin/wisoft/io/quotation/util/SaltUtil.kt
> +class SaltUtil {
@kukjun util class는 object로 선언해서 싱글턴으로 사용하는게 좋을 것 같아요. object로 하면 static 객체라서 따로 의존 주입안해주어도 됩니다. 지금 service 쪽에서 유틸 클래스를 주입받아 사용하다보니 가독성이 조금 떨어져요.
SaltUtil도 동일

2024-03-27 09:53 UTC, qkrcksduf commented on src/main/kotlin/wisoft/io/quotation/domain/User.kt
> +    fun isEnrolled(): Boolean {
@kukjun 단순하게 checkExists는 어떤지? 단어를 잘몰라서 인지는 모르겠는데 그렇게 와닿지 않는다랄까?

2024-03-27 09:53 UTC, qkrcksduf approved these changes

2024-03-27 09:55 UTC, qkrcksduf commented
@kukjun 너무 오래 pr 잡아둔 것 같아서 일단 풀었어요. 테스트 코드 작성하다보면 어차피 더 수정 해야할 수도 있어서 위에서 말한 내용이나 추가 refactoring은 테스트 코드 작성 pr에서 해두 돼요. 현재 pr 에서 해도되고 편한대루요~

2024-03-27 10:02 UTC, qkrcksduf commented on src/main/kotlin/wisoft/io/quotation/adaptor/in/http/UserController.kt
> +        println("request: $request")
@kukjun 제거 필요

2024-03-27 10:02 UTC, qkrcksduf commented on src/main/kotlin/wisoft/io/quotation/application/service/UserService.kt
> +            val ids = LinkedList<String>()
@kukjun request는 List가 아닌데 list 변환하는 이유가??

2024-03-27 10:02 UTC, qkrcksduf commented on src/main/kotlin/wisoft/io/quotation/adaptor/out/persistence/repository/UserCustomRepository.kt
> +                andCount += 1
추가로 동적쿼리 or 복잡한 조회가 아닌이상 nativeQuery 사용은 지양(유지보수가 좋지 않아요). 이 쿼리에서 name으로 조회, nickname으로 조회 하면 굳이 custom repository 필요없이 구현 가능.

2024-03-28 07:15 UTC, kukjun commented
말씀해주시는 Refactoring 부분은 새로 만드는 issue에서 작업해둘게요

2024-03-28 07:15 UTC, merged

2024-03-28 11:26 UTC, kukjun reviewed
@qkrcksduf Merge되긴 했지만 해당 Comment에 궁금한점이 남았습니다.

답변 주시면 감사하겠습니다.

2024-03-28 11:26 UTC, kukjun commented on src/main/kotlin/wisoft/io/quotation/application/service/UserService.kt
> +            val ids = LinkedList<String>()
@qkrcksduf 
User List 조회하는 API가 여기 뿐 아니라 다른 곳에서도 쓰일 수 있다고 생각했어요.

User List 조회는 사실 여러개를 조회할 수 있어야 하는데 저희가 사용하는 방식은 단일 조회 밖에 일어날 수 없어서, id, nickname의 List를 받아서 다른때에도 쓸 수 있게 하려고 했어요.

Ids, Nicknames를 받는 방식은 문제가 있어 보입니다. 리팩토링 해둘게요

2024-03-28 11:26 UTC, kukjun commented on src/main/kotlin/wisoft/io/quotation/domain/User.kt
> +    fun isEnrolled(): Boolean {
@qkrcksduf 확인했습니다.

boolean 리턴에서 check라는 이름의 메서드를 별로 선호하지 않습니다! (check라는 단어가 주는 애매함)
Enrolled라는 단어는 등록된 이라는 뜻인데, 조금 애매하면 isDeleted 라는 단어로 변경하고 로직을 조금 수정하는건 어떨까요?

2024-03-28 11:26 UTC, kukjun commented on src/main/kotlin/wisoft/io/quotation/util/SaltUtil.kt
> +class SaltUtil {
@qkrcksduf SaltUtil class는 object로 전환하는게 문제가 없습니다.

그런데 JWTUtil은 .yml 파일에서 값을 읽어오다보니, 초기화 시점에 이미 만들어져 설정값을 주입받지 못하는 문제가 ... 🙄
그래서 사용이 안되는 줄 알고 저렇게 사용했는데 혹시 방법이 있을까요?

2024-03-28 11:26 UTC, kukjun commented on src/main/kotlin/wisoft/io/quotation/application/port/in/CreateUserUseCase.kt
>          val id: String,
둘다 필수라고 생각하고 있어요.

혹시 서비스 쪽 코드 변경이 어떻게 일어나야 하나요?